server:
  port: 8999
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
security:
  basic:
    enabled: false

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    goshopping:  #路由 名字
      path: /gs/**
      serviceId: goshopping-service
    authorization:
      path: /as/**
      serviceId: authorization-service
    order:
      path: /os/**
      serviceId: order-service
    vip:
      path: /vs/**
      serviceId: vip-service
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  60000
ribbon:
  ReadTimeout:  10000
  SocketTimeout:  10000


#  ratelimit:
#    enabled: true
#    default-policy:
#        limit: 10
#        refresh-interval: 60
#        type: origin
